name: Deploy Website

on:
  push:
    tags:
      - "@hrc/*" # matches @hrc/package-name
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # based on https://stackoverflow.com/a/72959712
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "{name}=branch" >> $GITHUB_OUTPUT
          echo "current branch: $branch"

  changed-files:
    needs: check-branch
    name: Get changed files
    if: ${{ needs.check-branch.outputs.branch == 'master' }}
    outputs:
      files: ${{ steps.filter.outputs.any_changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: tj-actions/changed-files@v44
        id: filter
        with:
          files: |
            website/**

  build:
    needs: changed-files
    runs-on: ubuntu-latest
    if: ${{ needs.changed-files.outputs.files == 'true' }}
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Set up Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build website
        run: pnpm nx build @hrc/website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/dist

  deploy:
    needs: [changed-files, build]
    runs-on: ubuntu-latest
    if: ${{ needs.changed-files.outputs.files == 'true' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
