# based on https://github.com/vitejs/vite/blob/main/.github/workflows/release-tag.yml
name: GitHub release tag

on:
  push:
    tags-ignore:
      - "@hrc/website" # exclude website

jobs:
  release:
    if: github.repository == 'Hdoc1509/hrc'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get package name for tag
        id: tag
        run: |
          # based on https://stackoverflow.com/a/4170409
          # @hrc/package-name@1.2.3 -> package-name
          pkg_name="${GITHUB_REF_NAME%@*}" # truncates from last '@'
          pkg_name_without_scope="${pkg_name#*/}" # truncates until first '/'
          echo "pkg_name=$pkg_name_without_scope" >> $GITHUB_OUTPUT

      - name: Create release
        if: steps.tag.outputs.pkg_name
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/Hdoc1509/hrc/blob/${{ github.ref_name }}/packages/${{ steps.tag.outputs.pkg_name }}/CHANGELOG.md) for details.
